[package]
name = "maven-hasher"
version = "0.1.0"
authors = ["covers1624 <laughlan.cov@internode.on.net>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
ring = "0.17.0-alpha.8"
walkdir = "2.3.1"
task_queue = "0.0.7"
md5 = "0.7.0"
data-encoding="2.3.1"
num_cpus="1.13.0"